[sandbox]
runtime  = "node"
setup    = "npm install"
dev      = "node server.js"
port     = 3000
resources = "small"
services = ["postgres", "redis"]

[sandbox.postgres]
template = "neon:mute-heart-39788598/br-old-moon-adnvt9qw"
env      = "DATABASE_URL"

[sandbox.redis]
env      = "REDIS_URL"
